services:
  web:
    build:
      context: .
      target: dev
    environment:
      - DJANGO_SETTINGS_MODULE=movie_info_demo.settings.local  # <- Add this line
      - DEBUG=true
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
